--
-- PostgreSQL database dump
--

\restrict E4MPJWGJ13C6EKXAfG2jc0si2v1eHjIuxtx5URJWUfVFGoc03hx2wvfMf9CukuM

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-11-15 11:09:01

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 275 (class 1255 OID 453690)
-- Name: check_semaine_creation(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.check_semaine_creation() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    current_monday date;
    next_monday date;
    week_after_next date;
    exists_current_week BOOLEAN;
BEGIN
    ------------------------------------------------------------------------
    -- Calcul de la semaine courante (lundi)
    ------------------------------------------------------------------------
    current_monday := CURRENT_DATE - ((EXTRACT(DOW FROM CURRENT_DATE)::int + 6) % 7);

    -- Calcul du lundi suivant (semaine suivante)
    next_monday := current_monday + 7;

    -- Calcul de la semaine après la semaine suivante
    week_after_next := current_monday + 14;

    ------------------------------------------------------------------------
    -- 1ère vérification : bloquer si date_debut > semaine suivante
    ------------------------------------------------------------------------
    IF NEW.date_debut > next_monday THEN
        RAISE EXCEPTION
        'Vous ne pouvez pas créer un emploi du temps pour une semaine supérieure à la semaine suivante (%).',
        next_monday;
    END IF;

    ------------------------------------------------------------------------
    -- 2ème vérification : si l'utilisateur crée la semaine suivante,
    -- vérifier que la semaine courante existe
    ------------------------------------------------------------------------
    IF NEW.date_debut = next_monday THEN
        SELECT EXISTS (
            SELECT 1
            FROM semaine_emploi_temps
            WHERE created_by_id = NEW.created_by_id
            AND date_debut = current_monday
        ) INTO exists_current_week;

        IF NOT exists_current_week THEN
            RAISE EXCEPTION
            'Vous ne pouvez pas créer la semaine du lundi % car la semaine courante du lundi % doit d’abord exister.',
            next_monday, current_monday;
        END IF;
    END IF;

    -- Si date_debut = current_monday (semaine courante) → pas de blocage
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.check_semaine_creation() OWNER TO postgres;

--
-- TOC entry 274 (class 1255 OID 453686)
-- Name: limit_semaine_emploi_temps(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.limit_semaine_emploi_temps() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- Supprimer les semaines les plus anciennes si un responsable dépasse 2
    DELETE FROM semaine_emploi_temps
    WHERE id IN (
        SELECT id
        FROM semaine_emploi_temps
        WHERE created_by_id = NEW.created_by_id
        ORDER BY created_at ASC
        OFFSET 2  -- Conserve les 2 plus récentes
    );

    RETURN NEW;
END;
$$;


ALTER FUNCTION public.limit_semaine_emploi_temps() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 428813)
-- Name: academic_year; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.academic_year (
    id bigint NOT NULL,
    active boolean NOT NULL,
    end_date date,
    label character varying(255),
    start_date date
);


ALTER TABLE public.academic_year OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 428816)
-- Name: academic_year_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.academic_year ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academic_year_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 428817)
-- Name: admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin (
    id bigint NOT NULL,
    email character varying(255),
    full_name character varying(255),
    matricule character varying(255) NOT NULL,
    sexe_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.admin OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 428822)
-- Name: admin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 428823)
-- Name: app_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_user (
    id bigint NOT NULL,
    fcm_token character varying(255),
    password character varying(255) NOT NULL,
    privacy_policy_accepted_at timestamp(6) with time zone,
    role character varying(255) NOT NULL,
    username character varying(100) NOT NULL,
    CONSTRAINT app_user_role_check CHECK (((role)::text = ANY (ARRAY[('ADMIN'::character varying)::text, ('PROFESSEUR'::character varying)::text, ('ETUDIANT'::character varying)::text, ('SURVEILLANT'::character varying)::text, ('RESPONSABLE'::character varying)::text])))
);


ALTER TABLE public.app_user OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 428829)
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 428830)
-- Name: attendance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attendance (
    id bigint NOT NULL,
    scanneed_at timestamp(6) without time zone,
    scanned_at timestamp(6) without time zone,
    source character varying(255),
    status character varying(255) NOT NULL,
    "timestamp" timestamp(6) with time zone,
    session_id bigint NOT NULL,
    student_year_profile_id bigint NOT NULL,
    CONSTRAINT attendance_source_check CHECK (((source)::text = ANY (ARRAY[('qr'::character varying)::text, ('manual'::character varying)::text, ('offline'::character varying)::text]))),
    CONSTRAINT attendance_status_check CHECK (((status)::text = ANY (ARRAY[('PRESENT'::character varying)::text, ('ABSENT'::character varying)::text, ('PENDING'::character varying)::text])))
);


ALTER TABLE public.attendance OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 428837)
-- Name: attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 428838)
-- Name: campus; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campus (
    id bigint NOT NULL,
    address character varying(255),
    name character varying(255)
);


ALTER TABLE public.campus OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 428843)
-- Name: campus_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 428844)
-- Name: course; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    title character varying(255)
);


ALTER TABLE public.course OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 428849)
-- Name: course_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 428850)
-- Name: course_report; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_report (
    id bigint NOT NULL,
    description character varying(255),
    title character varying(255),
    course_id bigint NOT NULL,
    student_year_profile_id bigint NOT NULL
);


ALTER TABLE public.course_report OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 428855)
-- Name: course_report_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.course_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 428856)
-- Name: department; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.department (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.department OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 428859)
-- Name: department_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 453624)
-- Name: emploi_temps; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.emploi_temps (
    id bigint NOT NULL,
    annee_academique_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    niveau_id bigint NOT NULL,
    notes text,
    specialite_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    title character varying(255),
    created_by_id bigint NOT NULL,
    semaine_id bigint NOT NULL
);


ALTER TABLE public.emploi_temps OWNER TO postgres;

--
-- TOC entry 268 (class 1259 OID 453623)
-- Name: emploi_temps_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.emploi_temps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.emploi_temps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 428870)
-- Name: enrollment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enrollment (
    id bigint NOT NULL,
    student_year_profile_id bigint NOT NULL
);


ALTER TABLE public.enrollment OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 428873)
-- Name: enrollment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.enrollment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enrollment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 445197)
-- Name: exam_document; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exam_document (
    id bigint NOT NULL,
    category character varying(30) NOT NULL,
    compressed boolean NOT NULL,
    deleted boolean NOT NULL,
    deleted_at timestamp(6) with time zone,
    format character varying(20) NOT NULL,
    mime_type character varying(255),
    original_filename character varying(255) NOT NULL,
    size_bytes bigint,
    storage_path character varying(255) NOT NULL,
    stored_filename character varying(255) NOT NULL,
    uploaded_at timestamp(6) with time zone,
    uuid character varying(36) NOT NULL,
    visibility character varying(255),
    academic_year_id bigint,
    level_id bigint,
    uploader_id bigint,
    CONSTRAINT exam_document_category_check CHECK (((category)::text = ANY ((ARRAY['EXAM'::character varying, 'CC'::character varying, 'SUPPORT'::character varying, 'TD'::character varying, 'TP'::character varying, 'QUIZ'::character varying, 'ANNEXE'::character varying, 'AUTRE'::character varying])::text[]))),
    CONSTRAINT exam_document_format_check CHECK (((format)::text = ANY ((ARRAY['PDF'::character varying, 'DOCX'::character varying, 'DOC'::character varying, 'XLSX'::character varying, 'PPTX'::character varying, 'CSV'::character varying, 'ZIP'::character varying, 'JPG'::character varying, 'PNG'::character varying, 'MP4'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT exam_document_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying, 'ONLY_COURSE'::character varying])::text[])))
);


ALTER TABLE public.exam_document OWNER TO postgres;

--
-- TOC entry 266 (class 1259 OID 445207)
-- Name: exam_document_course; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exam_document_course (
    exam_document_id bigint NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE public.exam_document_course OWNER TO postgres;

--
-- TOC entry 264 (class 1259 OID 445196)
-- Name: exam_document_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exam_document ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 445212)
-- Name: exam_document_specialty; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exam_document_specialty (
    exam_document_id bigint NOT NULL,
    specialty_id bigint NOT NULL
);


ALTER TABLE public.exam_document_specialty OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 428874)
-- Name: level; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.level (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.level OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 428877)
-- Name: level_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.level ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.level_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 273 (class 1259 OID 453664)
-- Name: ligne_emploi_temps; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ligne_emploi_temps (
    id bigint NOT NULL,
    cours_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    heure_debut time(6) without time zone NOT NULL,
    heure_fin time(6) without time zone NOT NULL,
    jour character varying(16) NOT NULL,
    ordre_small integer,
    plage_horaire_id bigint,
    professeur_id bigint,
    salle_id bigint,
    emploi_temps_id bigint NOT NULL,
    CONSTRAINT ligne_emploi_temps_jour_check CHECK (((jour)::text = ANY ((ARRAY['LUNDI'::character varying, 'MARDI'::character varying, 'MERCREDI'::character varying, 'JEUDI'::character varying, 'VENDREDI'::character varying, 'SAMEDI'::character varying, 'DIMANCHE'::character varying])::text[])))
);


ALTER TABLE public.ligne_emploi_temps OWNER TO postgres;

--
-- TOC entry 272 (class 1259 OID 453663)
-- Name: ligne_emploi_temps_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ligne_emploi_temps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ligne_emploi_temps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 428888)
-- Name: notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    message text,
    is_read boolean,
    title character varying(255),
    destinataire_user_id bigint NOT NULL,
    user_id bigint
);


ALTER TABLE public.notification OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 428893)
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 428894)
-- Name: plages_horaires; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plages_horaires (
    id bigint NOT NULL,
    libelle character varying(255) NOT NULL
);


ALTER TABLE public.plages_horaires OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 428897)
-- Name: plages_horaires_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.plages_horaires ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plages_horaires_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 428898)
-- Name: responsable; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.responsable (
    id bigint NOT NULL,
    email character varying(255),
    full_name character varying(255),
    matricule character varying(255) NOT NULL,
    sexe_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.responsable OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 428903)
-- Name: responsable_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.responsable ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.responsable_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 428904)
-- Name: room; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.room (
    id bigint NOT NULL,
    capacity integer,
    name character varying(255),
    campus_id bigint NOT NULL
);


ALTER TABLE public.room OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 428907)
-- Name: room_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 271 (class 1259 OID 453632)
-- Name: semaine_emploi_temps; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.semaine_emploi_temps (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    date_debut date NOT NULL,
    date_fin date NOT NULL,
    updated_at timestamp(6) with time zone,
    created_by_id bigint NOT NULL
);


ALTER TABLE public.semaine_emploi_temps OWNER TO postgres;

--
-- TOC entry 270 (class 1259 OID 453631)
-- Name: semaine_emploi_temps_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.semaine_emploi_temps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.semaine_emploi_temps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 428912)
-- Name: session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.session (
    id bigint NOT NULL,
    closed boolean,
    created timestamp(6) without time zone,
    end_time timestamp(6) without time zone,
    expiry_time timestamp(6) without time zone,
    notified boolean,
    qr_payload text,
    qr_token text,
    start_time timestamp(6) without time zone,
    academic_year_id bigint NOT NULL,
    campus_id bigint NOT NULL,
    course_id bigint NOT NULL,
    expected_level_id bigint NOT NULL,
    expected_specialty_id bigint NOT NULL,
    room_id bigint NOT NULL,
    surveillant_id bigint,
    teacher_year_profile_id bigint,
    user_id bigint NOT NULL
);


ALTER TABLE public.session OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 428917)
-- Name: session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 428918)
-- Name: sexe; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sexe (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.sexe OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 428921)
-- Name: sexe_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sexe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sexe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 428922)
-- Name: specialty; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.specialty (
    id bigint NOT NULL,
    name character varying(255),
    department_id bigint
);


ALTER TABLE public.specialty OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 428925)
-- Name: specialty_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.specialty ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.specialty_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 428926)
-- Name: statuts_emploi_temps; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.statuts_emploi_temps (
    id bigint NOT NULL,
    libelle character varying(255) NOT NULL
);


ALTER TABLE public.statuts_emploi_temps OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 428929)
-- Name: statuts_emploi_temps_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.statuts_emploi_temps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.statuts_emploi_temps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 428930)
-- Name: student; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student (
    id bigint NOT NULL,
    avatar_url character varying(255),
    email character varying(255) NOT NULL,
    full_name character varying(255),
    matricule character varying(255) NOT NULL,
    sexe_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.student OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 428935)
-- Name: student_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 428936)
-- Name: student_year_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_year_profile (
    id bigint NOT NULL,
    active boolean NOT NULL,
    academic_year_id bigint NOT NULL,
    level_id bigint NOT NULL,
    specialty_id bigint NOT NULL,
    student_id bigint NOT NULL
);


ALTER TABLE public.student_year_profile OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 428939)
-- Name: student_year_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_year_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_year_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 428940)
-- Name: surveillant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.surveillant (
    id bigint NOT NULL,
    email character varying(255),
    full_name character varying(255),
    matricule character varying(255) NOT NULL,
    sexe_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.surveillant OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 428945)
-- Name: surveillant_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.surveillant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.surveillant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 428946)
-- Name: teacher; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teacher (
    id bigint NOT NULL,
    email character varying(255),
    full_name character varying(255),
    matricule character varying(255) NOT NULL,
    sexe_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.teacher OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 428951)
-- Name: teacher_courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teacher_courses (
    teacher_id bigint NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE public.teacher_courses OWNER TO postgres;

--
-- TOC entry 261 (class 1259 OID 428954)
-- Name: teacher_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teacher ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 262 (class 1259 OID 428955)
-- Name: teacher_year_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teacher_year_profile (
    id bigint NOT NULL,
    active boolean NOT NULL,
    academic_year_id bigint NOT NULL,
    teacher_id bigint NOT NULL
);


ALTER TABLE public.teacher_year_profile OWNER TO postgres;

--
-- TOC entry 263 (class 1259 OID 428958)
-- Name: teacher_year_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teacher_year_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_year_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4848 (class 2606 OID 428962)
-- Name: academic_year academic_year_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.academic_year
    ADD CONSTRAINT academic_year_pkey PRIMARY KEY (id);


--
-- TOC entry 4850 (class 2606 OID 428964)
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (id);


--
-- TOC entry 4858 (class 2606 OID 428966)
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4864 (class 2606 OID 428968)
-- Name: attendance attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);


--
-- TOC entry 4876 (class 2606 OID 428970)
-- Name: campus campus_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campus
    ADD CONSTRAINT campus_pkey PRIMARY KEY (id);


--
-- TOC entry 4880 (class 2606 OID 428972)
-- Name: course course_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_pkey PRIMARY KEY (id);


--
-- TOC entry 4884 (class 2606 OID 428974)
-- Name: course_report course_report_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_report
    ADD CONSTRAINT course_report_pkey PRIMARY KEY (id);


--
-- TOC entry 4886 (class 2606 OID 428976)
-- Name: department department_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (id);


--
-- TOC entry 4982 (class 2606 OID 453630)
-- Name: emploi_temps emploi_temps_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emploi_temps
    ADD CONSTRAINT emploi_temps_pkey PRIMARY KEY (id);


--
-- TOC entry 4890 (class 2606 OID 428982)
-- Name: enrollment enrollment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrollment
    ADD CONSTRAINT enrollment_pkey PRIMARY KEY (id);


--
-- TOC entry 4978 (class 2606 OID 445211)
-- Name: exam_document_course exam_document_course_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_document_course
    ADD CONSTRAINT exam_document_course_pkey PRIMARY KEY (exam_document_id, course_id);


--
-- TOC entry 4970 (class 2606 OID 445206)
-- Name: exam_document exam_document_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_document
    ADD CONSTRAINT exam_document_pkey PRIMARY KEY (id);


--
-- TOC entry 4980 (class 2606 OID 445216)
-- Name: exam_document_specialty exam_document_specialty_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_document_specialty
    ADD CONSTRAINT exam_document_specialty_pkey PRIMARY KEY (exam_document_id, specialty_id);


--
-- TOC entry 4894 (class 2606 OID 428984)
-- Name: level level_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.level
    ADD CONSTRAINT level_pkey PRIMARY KEY (id);


--
-- TOC entry 4993 (class 2606 OID 453669)
-- Name: ligne_emploi_temps ligne_emploi_temps_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ligne_emploi_temps
    ADD CONSTRAINT ligne_emploi_temps_pkey PRIMARY KEY (id);


--
-- TOC entry 4898 (class 2606 OID 428990)
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- TOC entry 4900 (class 2606 OID 428992)
-- Name: plages_horaires plages_horaires_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plages_horaires
    ADD CONSTRAINT plages_horaires_pkey PRIMARY KEY (id);


--
-- TOC entry 4904 (class 2606 OID 428994)
-- Name: responsable responsable_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.responsable
    ADD CONSTRAINT responsable_pkey PRIMARY KEY (id);


--
-- TOC entry 4912 (class 2606 OID 428996)
-- Name: room room_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT room_pkey PRIMARY KEY (id);


--
-- TOC entry 4988 (class 2606 OID 453636)
-- Name: semaine_emploi_temps semaine_emploi_temps_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.semaine_emploi_temps
    ADD CONSTRAINT semaine_emploi_temps_pkey PRIMARY KEY (id);


--
-- TOC entry 4920 (class 2606 OID 429000)
-- Name: session session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT session_pkey PRIMARY KEY (id);


--
-- TOC entry 4924 (class 2606 OID 429002)
-- Name: sexe sexe_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sexe
    ADD CONSTRAINT sexe_pkey PRIMARY KEY (id);


--
-- TOC entry 4928 (class 2606 OID 429004)
-- Name: specialty specialty_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specialty
    ADD CONSTRAINT specialty_pkey PRIMARY KEY (id);


--
-- TOC entry 4930 (class 2606 OID 429006)
-- Name: statuts_emploi_temps statuts_emploi_temps_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.statuts_emploi_temps
    ADD CONSTRAINT statuts_emploi_temps_pkey PRIMARY KEY (id);


--
-- TOC entry 4935 (class 2606 OID 429008)
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (id);


--
-- TOC entry 4945 (class 2606 OID 429010)
-- Name: student_year_profile student_year_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_year_profile
    ADD CONSTRAINT student_year_profile_pkey PRIMARY KEY (id);


--
-- TOC entry 4949 (class 2606 OID 429012)
-- Name: surveillant surveillant_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.surveillant
    ADD CONSTRAINT surveillant_pkey PRIMARY KEY (id);


--
-- TOC entry 4958 (class 2606 OID 429014)
-- Name: teacher teacher_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT teacher_pkey PRIMARY KEY (id);


--
-- TOC entry 4966 (class 2606 OID 429016)
-- Name: teacher_year_profile teacher_year_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher_year_profile
    ADD CONSTRAINT teacher_year_profile_pkey PRIMARY KEY (id);


--
-- TOC entry 4852 (class 2606 OID 429018)
-- Name: admin uk11nr14q4xirvd39hkaw39e7j0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT uk11nr14q4xirvd39hkaw39e7j0 UNIQUE (matricule);


--
-- TOC entry 4888 (class 2606 OID 429020)
-- Name: department uk1t68827l97cwyxo9r1u6t4p7d; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT uk1t68827l97cwyxo9r1u6t4p7d UNIQUE (name);


--
-- TOC entry 4902 (class 2606 OID 429022)
-- Name: plages_horaires uk2gbgwu435q44ceuywwactb5b; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plages_horaires
    ADD CONSTRAINT uk2gbgwu435q44ceuywwactb5b UNIQUE (libelle);


--
-- TOC entry 4862 (class 2606 OID 429024)
-- Name: app_user uk3k4cplvh82srueuttfkwnylq0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT uk3k4cplvh82srueuttfkwnylq0 UNIQUE (username);


--
-- TOC entry 4960 (class 2606 OID 429026)
-- Name: teacher uk3kv6k1e64a9gylvkn3gnghc2q; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT uk3kv6k1e64a9gylvkn3gnghc2q UNIQUE (email);


--
-- TOC entry 4947 (class 2606 OID 429028)
-- Name: student_year_profile uk7v49vq4pgvdpg5082y71cd8wc; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_year_profile
    ADD CONSTRAINT uk7v49vq4pgvdpg5082y71cd8wc UNIQUE (student_id, academic_year_id);


--
-- TOC entry 4878 (class 2606 OID 429030)
-- Name: campus uk81rhu9trr93hw9082igcywgl8; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campus
    ADD CONSTRAINT uk81rhu9trr93hw9082igcywgl8 UNIQUE (name);


--
-- TOC entry 4951 (class 2606 OID 429032)
-- Name: surveillant uk967qr0dit8mdsgqys26fmoajv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.surveillant
    ADD CONSTRAINT uk967qr0dit8mdsgqys26fmoajv UNIQUE (matricule);


--
-- TOC entry 4906 (class 2606 OID 429034)
-- Name: responsable ukb602l7w7bwijvmcrti2dt4tbu; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.responsable
    ADD CONSTRAINT ukb602l7w7bwijvmcrti2dt4tbu UNIQUE (email);


--
-- TOC entry 4937 (class 2606 OID 429036)
-- Name: student ukbkix9btnoi1n917ll7bplkvg5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT ukbkix9btnoi1n917ll7bplkvg5 UNIQUE (user_id);


--
-- TOC entry 4854 (class 2606 OID 429038)
-- Name: admin ukc0r9atamxvbhjjvy5j8da1kam; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT ukc0r9atamxvbhjjvy5j8da1kam UNIQUE (email);


--
-- TOC entry 4939 (class 2606 OID 429040)
-- Name: student ukcdpum2apv0d0otcn04htkdwsn; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT ukcdpum2apv0d0otcn04htkdwsn UNIQUE (matricule);


--
-- TOC entry 4962 (class 2606 OID 429042)
-- Name: teacher ukcxk7jwdmm4mbssgsjlxqrqimb; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT ukcxk7jwdmm4mbssgsjlxqrqimb UNIQUE (matricule);


--
-- TOC entry 4953 (class 2606 OID 429044)
-- Name: surveillant ukdus5bwm8x789uwhk9sadonxaj; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.surveillant
    ADD CONSTRAINT ukdus5bwm8x789uwhk9sadonxaj UNIQUE (email);


--
-- TOC entry 4941 (class 2606 OID 429046)
-- Name: student ukfe0i52si7ybu0wjedj6motiim; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT ukfe0i52si7ybu0wjedj6motiim UNIQUE (email);


--
-- TOC entry 4908 (class 2606 OID 429048)
-- Name: responsable ukgwha7tvb9d95nvvrnqf9rp70b; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.responsable
    ADD CONSTRAINT ukgwha7tvb9d95nvvrnqf9rp70b UNIQUE (user_id);


--
-- TOC entry 4856 (class 2606 OID 429050)
-- Name: admin ukhawikyhwwfvbnog5byokutpff; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT ukhawikyhwwfvbnog5byokutpff UNIQUE (user_id);


--
-- TOC entry 4976 (class 2606 OID 445222)
-- Name: exam_document ukhw99hed6a6e1kr8hqerai9atp; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_document
    ADD CONSTRAINT ukhw99hed6a6e1kr8hqerai9atp UNIQUE (uuid);


--
-- TOC entry 4964 (class 2606 OID 429052)
-- Name: teacher uki5wqs2ds2vpmfpbcdxi9m2jvr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT uki5wqs2ds2vpmfpbcdxi9m2jvr UNIQUE (user_id);


--
-- TOC entry 4882 (class 2606 OID 429054)
-- Name: course uki60mruj0y7a7vs99dqpiye7en; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT uki60mruj0y7a7vs99dqpiye7en UNIQUE (code);


--
-- TOC entry 4922 (class 2606 OID 429056)
-- Name: session ukjmnkt09sef67xhdbxd3wh2w7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT ukjmnkt09sef67xhdbxd3wh2w7 UNIQUE (qr_token);


--
-- TOC entry 4932 (class 2606 OID 429058)
-- Name: statuts_emploi_temps ukjnqbhb78bj6xheot5aqafn4yy; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.statuts_emploi_temps
    ADD CONSTRAINT ukjnqbhb78bj6xheot5aqafn4yy UNIQUE (libelle);


--
-- TOC entry 4896 (class 2606 OID 429060)
-- Name: level uklrjnw0jty1fs19q56u0us8d0n; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.level
    ADD CONSTRAINT uklrjnw0jty1fs19q56u0us8d0n UNIQUE (name);


--
-- TOC entry 4955 (class 2606 OID 429062)
-- Name: surveillant ukmsn290pohrwventqlfardvypi; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.surveillant
    ADD CONSTRAINT ukmsn290pohrwventqlfardvypi UNIQUE (user_id);


--
-- TOC entry 4968 (class 2606 OID 429064)
-- Name: teacher_year_profile uknk3099rnga9d5j62f0jv3s2h5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher_year_profile
    ADD CONSTRAINT uknk3099rnga9d5j62f0jv3s2h5 UNIQUE (teacher_id, academic_year_id);


--
-- TOC entry 4871 (class 2606 OID 429066)
-- Name: attendance uknkwljwwbvapja1g33dd73ptc0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT uknkwljwwbvapja1g33dd73ptc0 UNIQUE (student_year_profile_id, session_id);


--
-- TOC entry 4926 (class 2606 OID 429070)
-- Name: sexe ukq9pelf8a6mf9u5qeo9d1b9ce3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sexe
    ADD CONSTRAINT ukq9pelf8a6mf9u5qeo9d1b9ce3 UNIQUE (name);


--
-- TOC entry 4892 (class 2606 OID 429072)
-- Name: enrollment ukqojug5kbf7qu1rx2tiolopldk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrollment
    ADD CONSTRAINT ukqojug5kbf7qu1rx2tiolopldk UNIQUE (student_year_profile_id);


--
-- TOC entry 4910 (class 2606 OID 429074)
-- Name: responsable uksyjq4owfcbljk51ro19whcj2s; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.responsable
    ADD CONSTRAINT uksyjq4owfcbljk51ro19whcj2s UNIQUE (matricule);


--
-- TOC entry 4873 (class 2606 OID 429076)
-- Name: attendance uniq_att_profile_session; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT uniq_att_profile_session UNIQUE (student_year_profile_id, session_id);


--
-- TOC entry 4985 (class 2606 OID 453639)
-- Name: emploi_temps uq_emploi_unique_per_week; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emploi_temps
    ADD CONSTRAINT uq_emploi_unique_per_week UNIQUE (semaine_id, specialite_id, niveau_id, annee_academique_id);


--
-- TOC entry 4990 (class 2606 OID 453642)
-- Name: semaine_emploi_temps uq_semaine_user_date_debut; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.semaine_emploi_temps
    ADD CONSTRAINT uq_semaine_user_date_debut UNIQUE (created_by_id, date_debut);


--
-- TOC entry 4859 (class 1259 OID 429081)
-- Name: idx_app_user_username; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_app_user_username ON public.app_user USING btree (username);


--
-- TOC entry 4865 (class 1259 OID 429082)
-- Name: idx_attendance_present; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_attendance_present ON public.attendance USING btree (session_id, student_year_profile_id) WHERE ((status)::text = 'PRESENT'::text);


--
-- TOC entry 4866 (class 1259 OID 429083)
-- Name: idx_attendance_session; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_attendance_session ON public.attendance USING btree (session_id);


--
-- TOC entry 4867 (class 1259 OID 429084)
-- Name: idx_attendance_session_profile; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_attendance_session_profile ON public.attendance USING btree (session_id, student_year_profile_id);


--
-- TOC entry 4868 (class 1259 OID 429085)
-- Name: idx_attendance_session_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_attendance_session_status ON public.attendance USING btree (session_id, status);


--
-- TOC entry 4869 (class 1259 OID 429086)
-- Name: idx_attendance_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_attendance_status ON public.attendance USING btree (status);


--
-- TOC entry 4983 (class 1259 OID 453637)
-- Name: idx_emploi_semaine; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_emploi_semaine ON public.emploi_temps USING btree (semaine_id);


--
-- TOC entry 4971 (class 1259 OID 445220)
-- Name: idx_examdoc_category; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_examdoc_category ON public.exam_document USING btree (category);


--
-- TOC entry 4972 (class 1259 OID 445218)
-- Name: idx_examdoc_level; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_examdoc_level ON public.exam_document USING btree (level_id);


--
-- TOC entry 4973 (class 1259 OID 445219)
-- Name: idx_examdoc_uploader; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_examdoc_uploader ON public.exam_document USING btree (uploader_id);


--
-- TOC entry 4974 (class 1259 OID 445217)
-- Name: idx_examdoc_year; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_examdoc_year ON public.exam_document USING btree (academic_year_id);


--
-- TOC entry 4991 (class 1259 OID 453670)
-- Name: idx_ligne_emploi; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ligne_emploi ON public.ligne_emploi_temps USING btree (emploi_temps_id, jour, heure_debut);


--
-- TOC entry 4986 (class 1259 OID 453640)
-- Name: idx_semaine_user_createdat; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_semaine_user_createdat ON public.semaine_emploi_temps USING btree (created_by_id, created_at DESC);


--
-- TOC entry 4913 (class 1259 OID 429093)
-- Name: idx_session_app_user_start_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_session_app_user_start_time ON public.session USING btree (user_id, start_time DESC);


--
-- TOC entry 4914 (class 1259 OID 429094)
-- Name: idx_session_expected_level; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_session_expected_level ON public.session USING btree (expected_level_id);


--
-- TOC entry 4915 (class 1259 OID 429095)
-- Name: idx_session_expected_specialty; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_session_expected_specialty ON public.session USING btree (expected_specialty_id);


--
-- TOC entry 4916 (class 1259 OID 429096)
-- Name: idx_session_starttime; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_session_starttime ON public.session USING btree (start_time);


--
-- TOC entry 4917 (class 1259 OID 429097)
-- Name: idx_session_surveillant; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_session_surveillant ON public.session USING btree (surveillant_id);


--
-- TOC entry 4918 (class 1259 OID 429098)
-- Name: idx_session_user_start_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_session_user_start_time ON public.session USING btree (user_id, start_time DESC);


--
-- TOC entry 4933 (class 1259 OID 429099)
-- Name: idx_student_fullname; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_student_fullname ON public.student USING btree (full_name);


--
-- TOC entry 4942 (class 1259 OID 429100)
-- Name: idx_syp_level_specialty_ay; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_syp_level_specialty_ay ON public.student_year_profile USING btree (level_id, specialty_id, academic_year_id);


--
-- TOC entry 4943 (class 1259 OID 429101)
-- Name: idx_syp_level_specialty_year; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_syp_level_specialty_year ON public.student_year_profile USING btree (level_id, specialty_id, academic_year_id);


--
-- TOC entry 4956 (class 1259 OID 429102)
-- Name: idx_teacher_fullname; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_teacher_fullname ON public.teacher USING btree (full_name);


--
-- TOC entry 4860 (class 1259 OID 429103)
-- Name: idx_user_username; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_username ON public.app_user USING btree (username);


--
-- TOC entry 4874 (class 1259 OID 429104)
-- Name: uq_attendance_session_profile; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_attendance_session_profile ON public.attendance USING btree (session_id, student_year_profile_id);


--
-- TOC entry 5041 (class 2620 OID 453691)
-- Name: semaine_emploi_temps tg_check_semaine_creation; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER tg_check_semaine_creation BEFORE INSERT OR UPDATE ON public.semaine_emploi_temps FOR EACH ROW EXECUTE FUNCTION public.check_semaine_creation();


--
-- TOC entry 5042 (class 2620 OID 453687)
-- Name: semaine_emploi_temps trg_limit_semaine_emploi_temps; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_limit_semaine_emploi_temps AFTER INSERT ON public.semaine_emploi_temps FOR EACH ROW EXECUTE FUNCTION public.limit_semaine_emploi_temps();


--
-- TOC entry 5003 (class 2606 OID 429110)
-- Name: responsable fk1xmmdvsh6b5p8h05q5fuxs6em; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.responsable
    ADD CONSTRAINT fk1xmmdvsh6b5p8h05q5fuxs6em FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- TOC entry 5006 (class 2606 OID 429115)
-- Name: session fk29f6r35kbg5e21gqv3972h8ta; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT fk29f6r35kbg5e21gqv3972h8ta FOREIGN KEY (expected_specialty_id) REFERENCES public.specialty(id);


--
-- TOC entry 5024 (class 2606 OID 429125)
-- Name: teacher fk2fun0xdr4vew4040wk1o3yk9j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT fk2fun0xdr4vew4040wk1o3yk9j FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- TOC entry 5022 (class 2606 OID 429130)
-- Name: surveillant fk33471iff5a2f1rysvpbmf9f41; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.surveillant
    ADD CONSTRAINT fk33471iff5a2f1rysvpbmf9f41 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- TOC entry 5018 (class 2606 OID 429135)
-- Name: student_year_profile fk3kguj9clgk5aiq6qbx8y3cvap; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_year_profile
    ADD CONSTRAINT fk3kguj9clgk5aiq6qbx8y3cvap FOREIGN KEY (academic_year_id) REFERENCES public.academic_year(id);


--
-- TOC entry 5001 (class 2606 OID 429140)
-- Name: notification fk3p5a9vnk9b74bfinl206x9po3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fk3p5a9vnk9b74bfinl206x9po3 FOREIGN KEY (destinataire_user_id) REFERENCES public.app_user(id);


--
-- TOC entry 5026 (class 2606 OID 429145)
-- Name: teacher_courses fk3s01r7lleqy78wd67qstdi74h; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher_courses
    ADD CONSTRAINT fk3s01r7lleqy78wd67qstdi74h FOREIGN KEY (teacher_id) REFERENCES public.teacher(id);


--
-- TOC entry 5007 (class 2606 OID 429150)
-- Name: session fk3ytt9yah3j54hpllng184c6kf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT fk3ytt9yah3j54hpllng184c6kf FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- TOC entry 5037 (class 2606 OID 453643)
-- Name: emploi_temps fk4bmhxgd7lqa0592rms3w4mmsd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emploi_temps
    ADD CONSTRAINT fk4bmhxgd7lqa0592rms3w4mmsd FOREIGN KEY (created_by_id) REFERENCES public.responsable(id);


--
-- TOC entry 5030 (class 2606 OID 445228)
-- Name: exam_document fk4gnvoa90b8nkg7t8s06qtdh3w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_document
    ADD CONSTRAINT fk4gnvoa90b8nkg7t8s06qtdh3w FOREIGN KEY (level_id) REFERENCES public.level(id);


--
-- TOC entry 5033 (class 2606 OID 445238)
-- Name: exam_document_course fk4qdf4oj8uuen7tbudbaf73mkw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_document_course
    ADD CONSTRAINT fk4qdf4oj8uuen7tbudbaf73mkw FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- TOC entry 5008 (class 2606 OID 429160)
-- Name: session fk5ibwg70x5r9hls6pqe5yg2vvb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT fk5ibwg70x5r9hls6pqe5yg2vvb FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- TOC entry 5035 (class 2606 OID 445253)
-- Name: exam_document_specialty fk85kp4xi68o2ek0kp92g3q8ax3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_document_specialty
    ADD CONSTRAINT fk85kp4xi68o2ek0kp92g3q8ax3 FOREIGN KEY (exam_document_id) REFERENCES public.exam_document(id);


--
-- TOC entry 5036 (class 2606 OID 445248)
-- Name: exam_document_specialty fk9bsetadu63lngm073i81ya4yx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_document_specialty
    ADD CONSTRAINT fk9bsetadu63lngm073i81ya4yx FOREIGN KEY (specialty_id) REFERENCES public.specialty(id);


--
-- TOC entry 5027 (class 2606 OID 429175)
-- Name: teacher_courses fk9rq50frjy5ol4a1wleykjaqv2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher_courses
    ADD CONSTRAINT fk9rq50frjy5ol4a1wleykjaqv2 FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- TOC entry 5025 (class 2606 OID 429180)
-- Name: teacher fka4lg9ib9kup56w4gnsil9n5x9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT fka4lg9ib9kup56w4gnsil9n5x9 FOREIGN KEY (sexe_id) REFERENCES public.sexe(id);


--
-- TOC entry 5023 (class 2606 OID 429185)
-- Name: surveillant fkaf8hujv0m4nbv259ro5qsw78a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.surveillant
    ADD CONSTRAINT fkaf8hujv0m4nbv259ro5qsw78a FOREIGN KEY (sexe_id) REFERENCES public.sexe(id);


--
-- TOC entry 5016 (class 2606 OID 429200)
-- Name: student fkaxsdm2gcisn33mjbp9hc4imps; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT fkaxsdm2gcisn33mjbp9hc4imps FOREIGN KEY (sexe_id) REFERENCES public.sexe(id);


--
-- TOC entry 5009 (class 2606 OID 429205)
-- Name: session fkcf2auxd2fyjuk05ua7nb62ioo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT fkcf2auxd2fyjuk05ua7nb62ioo FOREIGN KEY (campus_id) REFERENCES public.campus(id);


--
-- TOC entry 5010 (class 2606 OID 429210)
-- Name: session fkcmxbf3210jn9r0rsmi4shssmh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT fkcmxbf3210jn9r0rsmi4shssmh FOREIGN KEY (teacher_year_profile_id) REFERENCES public.teacher_year_profile(id);


--
-- TOC entry 5002 (class 2606 OID 429215)
-- Name: notification fkcxbqr6g1py0j4m9qeq44h1ju6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fkcxbqr6g1py0j4m9qeq44h1ju6 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- TOC entry 5017 (class 2606 OID 429220)
-- Name: student fkd5m4yhlpu19okmb1lpc8hsulv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT fkd5m4yhlpu19okmb1lpc8hsulv FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- TOC entry 5019 (class 2606 OID 429225)
-- Name: student_year_profile fkd8yl1wtix1hivdscfxw42p9ed; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_year_profile
    ADD CONSTRAINT fkd8yl1wtix1hivdscfxw42p9ed FOREIGN KEY (student_id) REFERENCES public.student(id);


--
-- TOC entry 5020 (class 2606 OID 429230)
-- Name: student_year_profile fkejh3ehmcfi3mi1ycb46kcqs7r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_year_profile
    ADD CONSTRAINT fkejh3ehmcfi3mi1ycb46kcqs7r FOREIGN KEY (level_id) REFERENCES public.level(id);


--
-- TOC entry 5039 (class 2606 OID 453658)
-- Name: semaine_emploi_temps fkerijtbd0ryxm5s9v71mvltv5c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.semaine_emploi_temps
    ADD CONSTRAINT fkerijtbd0ryxm5s9v71mvltv5c FOREIGN KEY (created_by_id) REFERENCES public.responsable(id);


--
-- TOC entry 5031 (class 2606 OID 445223)
-- Name: exam_document fkeyahqplejqf9uu6ht9ir36kwo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_document
    ADD CONSTRAINT fkeyahqplejqf9uu6ht9ir36kwo FOREIGN KEY (academic_year_id) REFERENCES public.academic_year(id);


--
-- TOC entry 4994 (class 2606 OID 429245)
-- Name: admin fkfxsnetonwehft3bspq930eehm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT fkfxsnetonwehft3bspq930eehm FOREIGN KEY (sexe_id) REFERENCES public.sexe(id);


--
-- TOC entry 4998 (class 2606 OID 429250)
-- Name: course_report fkgk6jy19gy59h6chorgshqfeup; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_report
    ADD CONSTRAINT fkgk6jy19gy59h6chorgshqfeup FOREIGN KEY (student_year_profile_id) REFERENCES public.student_year_profile(id);


--
-- TOC entry 5032 (class 2606 OID 445233)
-- Name: exam_document fkgvco150adpbu28xy10lmhoq8s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_document
    ADD CONSTRAINT fkgvco150adpbu28xy10lmhoq8s FOREIGN KEY (uploader_id) REFERENCES public.app_user(id);


--
-- TOC entry 4996 (class 2606 OID 429255)
-- Name: attendance fkh0vcn3639w6x5f41g0j8fe39s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fkh0vcn3639w6x5f41g0j8fe39s FOREIGN KEY (student_year_profile_id) REFERENCES public.student_year_profile(id);


--
-- TOC entry 5028 (class 2606 OID 429260)
-- Name: teacher_year_profile fkhheuhe7pu1kmxxe0cgrn0pxy2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher_year_profile
    ADD CONSTRAINT fkhheuhe7pu1kmxxe0cgrn0pxy2 FOREIGN KEY (teacher_id) REFERENCES public.teacher(id);


--
-- TOC entry 4995 (class 2606 OID 429265)
-- Name: admin fkhiuu8bqivf3wa1cvaowh04g02; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT fkhiuu8bqivf3wa1cvaowh04g02 FOREIGN KEY (user_id) REFERENCES public.app_user(id);


--
-- TOC entry 5011 (class 2606 OID 429270)
-- Name: session fkhmkyh79kh4mm63gr4jdw6lnn8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT fkhmkyh79kh4mm63gr4jdw6lnn8 FOREIGN KEY (academic_year_id) REFERENCES public.academic_year(id);


--
-- TOC entry 5040 (class 2606 OID 453681)
-- Name: ligne_emploi_temps fkipsql725ljtj1io215jun4imf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ligne_emploi_temps
    ADD CONSTRAINT fkipsql725ljtj1io215jun4imf FOREIGN KEY (emploi_temps_id) REFERENCES public.emploi_temps(id) ON DELETE CASCADE;


--
-- TOC entry 5034 (class 2606 OID 445243)
-- Name: exam_document_course fkj5np1rt8oyjr2wkiq3dvbbq5r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_document_course
    ADD CONSTRAINT fkj5np1rt8oyjr2wkiq3dvbbq5r FOREIGN KEY (exam_document_id) REFERENCES public.exam_document(id);


--
-- TOC entry 5015 (class 2606 OID 429280)
-- Name: specialty fklps74l72wvj96da9q5pnwyguk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specialty
    ADD CONSTRAINT fklps74l72wvj96da9q5pnwyguk FOREIGN KEY (department_id) REFERENCES public.department(id);


--
-- TOC entry 4999 (class 2606 OID 429285)
-- Name: course_report fkmtfytv8s1r3yeu7r7oudqlmpm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_report
    ADD CONSTRAINT fkmtfytv8s1r3yeu7r7oudqlmpm FOREIGN KEY (course_id) REFERENCES public.course(id);


--
-- TOC entry 5005 (class 2606 OID 429290)
-- Name: room fkn0s1bbso5i6oqpg2h09vsuaf7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT fkn0s1bbso5i6oqpg2h09vsuaf7 FOREIGN KEY (campus_id) REFERENCES public.campus(id);


--
-- TOC entry 5012 (class 2606 OID 429300)
-- Name: session fkoyfccms1psubki0cm7c92msrp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT fkoyfccms1psubki0cm7c92msrp FOREIGN KEY (room_id) REFERENCES public.room(id);


--
-- TOC entry 5000 (class 2606 OID 429305)
-- Name: enrollment fkpk4tsp1jplup9s0asirvvkccv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrollment
    ADD CONSTRAINT fkpk4tsp1jplup9s0asirvvkccv FOREIGN KEY (student_year_profile_id) REFERENCES public.student_year_profile(id);


--
-- TOC entry 5013 (class 2606 OID 429310)
-- Name: session fkpvba15sexxflfkvwjqxyroute; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT fkpvba15sexxflfkvwjqxyroute FOREIGN KEY (expected_level_id) REFERENCES public.level(id);


--
-- TOC entry 5029 (class 2606 OID 429315)
-- Name: teacher_year_profile fkpwm08w2mxslihc3vvch7052p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher_year_profile
    ADD CONSTRAINT fkpwm08w2mxslihc3vvch7052p FOREIGN KEY (academic_year_id) REFERENCES public.academic_year(id);


--
-- TOC entry 4997 (class 2606 OID 429320)
-- Name: attendance fkras5lsk62ds9j7f8myss8nwcs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fkras5lsk62ds9j7f8myss8nwcs FOREIGN KEY (session_id) REFERENCES public.session(id);


--
-- TOC entry 5014 (class 2606 OID 429325)
-- Name: session fks55dyp9t5icnggmvujkbbwsyn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT fks55dyp9t5icnggmvujkbbwsyn FOREIGN KEY (surveillant_id) REFERENCES public.surveillant(id);


--
-- TOC entry 5004 (class 2606 OID 429340)
-- Name: responsable fksxlsjk6d9wq4reoakj128gqv9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.responsable
    ADD CONSTRAINT fksxlsjk6d9wq4reoakj128gqv9 FOREIGN KEY (sexe_id) REFERENCES public.sexe(id);


--
-- TOC entry 5021 (class 2606 OID 429345)
-- Name: student_year_profile fktn9ur7gtq6yy7usvh2almcht; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_year_profile
    ADD CONSTRAINT fktn9ur7gtq6yy7usvh2almcht FOREIGN KEY (specialty_id) REFERENCES public.specialty(id);


--
-- TOC entry 5038 (class 2606 OID 453676)
-- Name: emploi_temps fkv5978lnnkvt6r9dldescpxn6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emploi_temps
    ADD CONSTRAINT fkv5978lnnkvt6r9dldescpxn6 FOREIGN KEY (semaine_id) REFERENCES public.semaine_emploi_temps(id) ON DELETE CASCADE;


-- Completed on 2025-11-15 11:09:02

--
-- PostgreSQL database dump complete
--

\unrestrict E4MPJWGJ13C6EKXAfG2jc0si2v1eHjIuxtx5URJWUfVFGoc03hx2wvfMf9CukuM

